CREATE OR REPLACE FUNCTION distancia(latitude1 decimal, longitude1 decimal, latitude2 decimal, longitude2 decimal) RETURNS decimal AS $$
DECLARE R DECIMAL DEFAULT 0.0;
DECLARE DLONG DECIMAL DEFAULT 0.0;
DECLARE DLAT DECIMAL DEFAULT 0.0;
DECLARE A DECIMAL DEFAULT 0.0;
DECLARE C DECIMAL DEFAULT 0.0;
DECLARE D DECIMAL DEFAULT 0.0;
DECLARE SIN_DELAT DECIMAL DEFAULT 0.0;
DECLARE SIN_DELONG DECIMAL DEFAULT 0.0;
DECLARE COS_LAT1 DECIMAL DEFAULT 0.0;
DECLARE COS_LAT2 DECIMAL DEFAULT 0.0;
BEGIN
  R := 6378.137;
  DLAT := (latitude2-(latitude1))*(PI()/180);
  DLONG := (longitude2-(longitude1))*(PI()/180);
  SIN_DELAT := (SIN(DLAT/2))*(SIN(DLAT/2));
  SIN_DELONG := (SIN(DLONG/2))*(SIN(DLONG/2));
  COS_LAT1 := (COS(latitude1*(PI()/180)));
  COS_LAT2 := (COS(latitude2*(PI()/180)));
  A := SIN_DELAT + ((COS_LAT1*COS_LAT2)*(SIN_DELONG));
  C := ATAN2(SQRT(A),(SQRT(1-A)))*2;
  D := (R*C)*1000;
  RETURN D;
END;
$$ LANGUAGE plpgsql;